version: '3.7'
services:
  api:
    image: docker.pkg.github.com/thinkideaapp/sensi-backend-init/sensi-backend-init-api:master
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    volumes:
      - ./:/app
    depends_on:
      - redis
      - mysql
    env_file: .env
    restart: always

  mysql:
    image: mysql:5.6
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    env_file: .env

  redis:
    image: redis
    ports:
      - ${CACHE_REDIS_PORT}:${CACHE_REDIS_PORT}
    env_file: .env
