from .address import AddressSchema
from .category import CategorySchema
from .child import ChildSchema
from .city import CitySchema
from .community import CommunitySchema
from .content import ContentSchema
from .country import CountrySchema
from .extra_material import ExtraMaterialSchema
from .group import GroupSchema
from .institution import InstitutionSchema
from .institution_address import InstitutionAddressSchema
from .maas import MaasSchema
from .main_company import MainCompanySchema
from .main_settings import MainSettingsSchema
from .notification import NotificationSchema
from .school_class import SchoolClassSchema
from .secretary import SecretarySchema
from .secretary_address import SecretaryAddressSchema
from .secretary_maas_rating import SecretaryMaasRatingSchema
from .state import StateSchema
from .team import TeamSchema
from .token import TokenSchema
from .user import UserSchema
from .week import WeekSchema
