"""empty message

Revision ID: 04487b2f4136
Revises: 444e546f257e
Create Date: 2022-12-20 17:33:35.910741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04487b2f4136'
down_revision = '444e546f257e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_institution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('user', sa.Column('relationship', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'parent_id')
    op.drop_column('user', 'relationship')
    op.drop_table('user_institution')
    # ### end Alembic commands ###
