"""empty message

Revision ID: 0f5d83ca8c1e
Revises: bb7e98f4003f
Create Date: 2023-01-12 14:17:29.543650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5d83ca8c1e'
down_revision = 'bb7e98f4003f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extra_material', sa.Column('school_class_id', sa.Integer(), nullable=True))
    op.add_column('extra_material', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'extra_material', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'extra_material', 'school_class', ['school_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extra_material', type_='foreignkey')
    op.drop_constraint(None, 'extra_material', type_='foreignkey')
    op.drop_column('extra_material', 'category_id')
    op.drop_column('extra_material', 'school_class_id')
    # ### end Alembic commands ###
