"""empty message

Revision ID: 3a098c199d1a
Revises: cf640d7b0e11
Create Date: 2023-01-18 11:15:10.695190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a098c199d1a'
down_revision = 'cf640d7b0e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
