"""empty message

Revision ID: 5630000b53f8
Revises: 365167e8407c
Create Date: 2022-12-23 15:36:49.476982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5630000b53f8'
down_revision = '365167e8407c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'team', 'institution', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'institution_id')
    # ### end Alembic commands ###
