"""empty message

Revision ID: f3a5ea6e2bd7
Revises: 04487b2f4136
Create Date: 2022-12-22 11:13:16.691448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a5ea6e2bd7'
down_revision = '04487b2f4136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institution', 'type')
    # ### end Alembic commands ###
